name: VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start VPS
        run: |
          echo "Hello, ini VM Ubuntu gratis dari GitHub!"
          uname -a
          whoami
          top -b -n 1 | head -20
