name: Free VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Info sistem
        run: |
          echo "Kamu sekarang ada di VM Linux GitHub"
          uname -a
          lsb_release -a
          free -h
